### PR TITLE
feature: ut_video_filter_file provides the ability to override the de…

### PR DESCRIPTION
**Pull request by dmzoneill**
…fault filters

### CODE REVIEW

**Comment by rednoah** [comment]
Well, I don't think custom video filters are the way to go. It's too complicated for most users. I would generally recommend just doing `filebot -rename` for files where the `amc script` is ill-suited for one reason or another.

**Comment by rednoah** [comment]
If an option were to be added to the `amc script`, I'd consider something like "accept all files larger than 1 GB" to override the built-in regex filter.

`filebot` is doing that internally and thus less script about "trailer" files:
https://www.filebot.net/forums/viewtopic.php?t=12986

**Comment by dmzoneill** [comment]
Well i think you should remove 'Trailer' altogether from the list of filters in the amc script.
There are over 10 pages of series with the world "trailer" in it.
https://thetvdb.com/search?query=trailer
And there are over 200 matches on imdb for trailer.
https://www.imdb.com/find?q=trailer&s=tt&ref_=fn_al_tt_mr

How many files you you download, that are a trailer?
If you are looking at a trailer, its probably on youtube or something?

Further more, if i was to download an episode or a movie with the word 'trailer' in it, why would they package the episode or movie with a trailer file also? seems less likely than a series or movie with the word trailer.

if we are talking about 4k video or even 8k going forward, a 1gb filter may become a similar, less than ideal workaround.

**Comment by rednoah** [comment]
Each pattern was added to the list because someone reported issues with files being processed in error, in some cases overwriting previously processed "good" files.

I'm not inclined to make changes since we have very little information on what kind of file paths the very large and diverse number of FileBot users use FileBot. We know that the current system works well, except for one specific somewhat popular series. We don't know what will happen if we change things. My educated guess would be some really really bad outcome (i.e. data loss) for some very small number of users.

That said, I've added the proposed change to make `Trailer Park Boys` work in the `amc script` since this is indeed something that has come up multiple times over time:
https://github.com/filebot/scripts/commit/b03122842f1acd03a90a381a62f9148564fc8163

The other "trailer" shows are just not supported in the `amc script` for the time being, unless it becomes an inconvenience for a good number of users. The GUI and CLI can be used to deal with those in the meanwhile.

**Comment by dmzoneill** [comment]
Thanks for your consideration Reinhard.
I will just develop my own then and hopefully it will continue to work with future filebot development.

You might consider a strategy pattern to get past this problem, so as to not stall future development of features etc.
This will allow you to version the software whilst keeping old behaviours for existing customers

```
filebot -script ..... ut_version=v2
```


```
interface AMC {
    def execute(n, m)
}

class AMCv1 implements AMC {
    def execute(n, m) { 
       // legacy filter logic
   }
}

class AMCv2 implements AMC {
    def execute(n, m) {
        // modern filter logic
    }
}
```

**Comment by rednoah** [comment]
The `--file-filter` option can be used for custom file filtering nowadays.

**Pull request closed without merging**
