### PR TITLE
Adding the ability to update kodi with username and password

### PR DESCRIPTION
**Pull request by mamanguy**
Use it with:
'kodi=< username >:< password >@<hostname/ip address>'

### CODE REVIEW

**Comment by Centterm** [comment]
As a couple of month have passed, whats the status? I am really relaying on this.

**Comment by rednoah** [comment]
I'm fairly sure that this feature is already supported. What have you tried so far? Do you have logs?

**Comment by Centterm** [comment]
It should work, but it doesn't. It seems to be related to special characters or so. In my case special characters are [percent-ecoded](https://en.wikipedia.org/wiki/Percent-encoding). I can confirm that the creds and the encoding are definitely working as I use them currently as a temporary bugfix to create my own json messages.

The strange part is that if I use the URL generated and shown in the log with curl or my browser (no matter which machine on the local network), everything works as aspected. I get a notification.

I altered details of the log and used '<abc>' to indicate those changes ;) 
```
Notify Kodi: [host:<Encoded Username>:<Encoded password>@<ipv4 ip>, port:<port>]
GET: http://<Encoded Username>:<Encoded password>@1<ipv4 ip>:<port>/jsonrpc?request=%7B%22jsonrpc%22%3A%222.0%22%2C%22method%22%3A%22GUI.ShowNotification%22%2C%22params%22%3A%7B%22title%22%3A%22FileBot+finished+processing+1+files%22%2C%22message%22%3A%22%5Cu2022+RandomMovie%22%2C%22image%22%3A%22https%3A%2F%2Fapp.filebot.net%2Ficon.png%22%7D%2C%22id%22%3A1%7D
IOException: Server returned HTTP response code: 401 for URL: http://<Encoded Username>:<Encoded password>@1<ipv4 ip>:<port>/jsonrpc?request=%7B%22jsonrpc%22%3A%222.0%22%2C%22method%22%3A%22GUI.ShowNotification%22%2C%22params%22%3A%7B%22title%22%3A%22FileBot+finished+processing+1+files%22%2C%22message%22%3A%22%5Cu2022+RandomMovie%22%2C%22image%22%3A%22https%3A%2F%2Fapp.filebot.net%2Ficon.png%22%7D%2C%22id%22%3A1%7D
```

**Comment by rednoah** [comment]
You can always use `--def exec` to call custom scripts to make custom `curl` requests.

**Comment by Centterm** [comment]
Before I post more details from the proxy I did some further testing. The Encoding/Special Characters doesn't seem to be the issue. I can choose what ever I want I get 401.
The body/json messages of request were the same. Only the header differed. There is no authorization in the filebot request.

Filebot Header

Filebot Header

Let me know when you have a preferred http proxy on linux. I am new to http proxies and tried 'Charles'.

**Comment by rednoah** [comment]
No response.

**Comment by rednoah** [comment]
Underlying API doesn't seem to take care of this, so it's not an easy fix. I recommend using `curl` in the meanwhile.

**Comment by Centterm** [comment]
Mhm too bad. For a more detailed notification I would need to parse the log output and recyle it in curl.

**Pull request closed without merging**
